# Generated by Django 2.2.2 on 2019-06-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customId', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=20)),
                ('formatedStartDate', models.CharField(max_length=20)),
                ('homeTeam_name', models.CharField(max_length=20)),
                ('awayTeam_name', models.CharField(max_length=20)),
                ('homeScore_current', models.IntegerField()),
                ('awayScore_current', models.IntegerField()),
                ('homeScore_period1', models.IntegerField()),
                ('awayScore_period1', models.IntegerField()),
                ('homeScore_period2', models.IntegerField()),
                ('awayScore_period2', models.IntegerField()),
                ('homeScore_period3', models.IntegerField()),
                ('awayScore_period3', models.IntegerField()),
            ],
        ),
    ]
