# Generated by Django 2.2.2 on 2019-06-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofascore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetable',
            name='event_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
