# Generated by Django 2.2.2 on 2019-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofascore', '0002_auto_20190630_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetable',
            name='odds_away',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livetable',
            name='odds_home',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
