# Generated by Django 2.2.2 on 2019-07-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofascore', '0003_auto_20190701_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livetable',
            old_name='awayScore_current',
            new_name='current_away',
        ),
        migrations.RenameField(
            model_name='livetable',
            old_name='awayScore_period1',
            new_name='current_home',
        ),
        migrations.RenameField(
            model_name='livetable',
            old_name='awayScore_period2',
            new_name='period1_away',
        ),
        migrations.RenameField(
            model_name='livetable',
            old_name='awayScore_period3',
            new_name='period1_home',
        ),
        migrations.RenameField(
            model_name='livetable',
            old_name='homeScore_current',
            new_name='period2_away',
        ),
        migrations.RenameField(
            model_name='livetable',
            old_name='homeScore_period1',
            new_name='period2_home',
        ),
        migrations.RenameField(
            model_name='livetable',
            old_name='homeScore_period2',
            new_name='period3_away',
        ),
        migrations.RenameField(
            model_name='livetable',
            old_name='homeScore_period3',
            new_name='period3_home',
        ),
    ]
