# Generated by Django 2.2.3 on 2019-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofascore', '0004_auto_20190702_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetable',
            name='tennis_ssmg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
